# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell"]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));`
    choco install 7zip cmake git InnoSetup ninja -y

SHELL ["cmd", "/S", "/C"]
RUN ` 
    # Download the Build Tools bootstrapper.
    curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe `
    `
    # Install Build Tools with the Microsoft.VisualStudio.Workload.AzureBuildTools workload, excluding workloads and components with known issues.
    && (start /w vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" `
    --add Microsoft.VisualStudio.Workload.NativeDesktop`
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    --add Microsoft.VisualStudio.Component.VC.MFC `
    --add Microsoft.VisualStudio.Component.VC.ATL`
    --add Microsoft.VisualStudio.Component.VC.ATLMFC`
    --add Microsoft.VisualStudio.Component.VC.x86.x64 `
    --add Microsoft.VisualStudio.Component.Windows11SDK.22000 `
    || IF "%ERRORLEVEL%"=="3010" EXIT 0) `
    `
    # Cleanup
    && del /q vs_buildtools.exe

RUN setx "PATH" "C:\Program Files\CMake\bin;%PATH%" /m

WORKDIR C:\workdir

ENTRYPOINT ["C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell", "-NoLogo", "-ExecutionPolicy", "Bypass"]
